Lms.Web/Controllers/KitapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Kys.Web.Business;
using Kys.Web.Helpers;
using Kys.Web.Models;
using Kys.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Lms.Web.Controllers
{
    public class KitapController : Controller
    {
        public IKitapServis _kitapServis;
        public IYayineviServis _yayineviServis;
        public IYazarServis _yazarServis;

        public KitapController(IKitapServis kitapServis, IYayineviServis yayineviServis, IYazarServis yazarServis)
        {
            _kitapServis = kitapServis;
            _yazarServis = yazarServis;
            _yayineviServis = yayineviServis;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            ViewBag.Yazarlar = "";
            ViewBag.Yayinevleri = "";

            return View();
        }

        public async Task<JsonResult> KitaplariGetir(KitapAramaViewModel model)
        {
            var sonuc = await _kitapServis.KitaplariVeyaKitapGetir(model);
            return Json(sonuc);
        }

        public async Task<IActionResult> KitapKayit(KitapKayitViewModel model)
        {
            var yayinevleri = await _yayineviServis.YayinevleriGetir();
            var yazarlar = await _yazarServis.YazarlariGetir();
            ViewBag.yazarlar = yazarlar;
            ViewBag.yayinevleri = yayinevleri;

            if (model.KitapKey.HasValue)
            {
                try
                {
                    return PartialView("~/Views/Kitap/_KitapKayitPartial.cshtml", model);
                }
                catch (Exception ex)
                {

                    throw ex;
                }                
            }

            return PartialView("~/Views/Kitap/_KitapKayitPartial.cshtml");
        }

        public async Task<IActionResult> KitapKayitGuncelle(KitapKayitGuncelleViewModel model)
        {
            var yayinevleri = await _yayineviServis.YayinevleriGetir();
            var yazarlar = await _yazarServis.YazarlariGetir();
            ViewBag.yazarlar = yazarlar;
            ViewBag.yayinevleri = yayinevleri;

            var kitap = await _kitapServis.KitapGetir(model);
            return PartialView("~/Views/Kitap/_KitapKayitGuncellePartial.cshtml",kitap.Data);
        }

        public async Task<SonucModel<KitapKayitViewModel>> KitapKaydet(KitapKayitViewModel model)
        {
            if (model != null)
            {
                model.Ad = Helper.ToTitleCase(model.Ad);
            }
            var sonuc = await _kitapServis.KitapKaydetGuncelle(model);
            return sonuc;
        }

        public async Task<SonucModel<KitapKayitSilViewModel>> KitapSil(KitapKayitSilViewModel model)
        {
            var sonuc = await _kitapServis.KitapSil(model);
            return sonuc;
        }
    }
}

Lms.Web/Controllers/UyeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Kys.Web.Business;
using Kys.Web.Helpers;
using Kys.Web.Models;
using Kys.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Kys.Web.Controllers
{
    public class UyeController : Controller
    {
        public IUyeServis _uyeServis;

        public UyeController(IUyeServis uyeServis)
        {
            _uyeServis = uyeServis;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<JsonResult> UyeleriGetir(UyeAramaViewModel model)
        {
            var sonuc = await _uyeServis.UyeVeyaUyeleriGetir(model);
            return Json(sonuc);
        }

        public IActionResult UyeKayit(UyeKayitViewModel model)
        {
            if (model != null)
            {
                return PartialView("~/Views/Uye/_UyeKayitPartial.cshtml", model);
            }

            return PartialView("~/Views/Uye/_UyeKayitPartial.cshtml");
        }

        public async Task<SonucModel<UyeKayitViewModel>> UyeKaydet(UyeKayitViewModel model)
        {
            if (model!= null)
            {
                model.Ad = Helper.ToTitleCase(model.Ad);
            }
            var sonuc = await _uyeServis.UyeKaydetGuncelle(model);
            return sonuc;
        }

        public async Task<IActionResult> UyeDetayGetir(int uyeKey)
        {
            var sonuc = await _uyeServis.UyeDetayGetir(uyeKey);

            return PartialView("~/Views/Uye/_UyeDetayPartial.cshtml",sonuc);
        }

        public async Task<IActionResult> OduncVer(int demirbasNo, int uyeKey)
        {
            OduncVerViewModel model = new OduncVerViewModel()
            {
                DemirbasNo = demirbasNo,
                UyeKey = uyeKey
            };
           
            var sonuc = await _uyeServis.OduncVer(model);
            return Json(sonuc);
        }

        public async Task<IActionResult> IadeAl(int oduncKey)
        {
            IadeAlViewModel model = new IadeAlViewModel()
            {
                OduncKey = oduncKey
            };

            var sonuc = await _uyeServis.IadeAl(model);
            return Json(sonuc);
        }

        public async Task<SonucModel<UyeKayitSilViewModel>> UyeSil(UyeKayitSilViewModel model)
        {
            var sonuc = await _uyeServis.UyeSil(model);
            return sonuc;
        }

    }
}

Lms.Web/Controllers/YazarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Kys.Web.Business;
using Kys.Web.Helpers;
using Kys.Web.Models;
using Kys.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Lms.Web.Controllers
{
    public class YazarController : Controller
    {
        public IYazarServis _yazarServis;

        public YazarController(IYazarServis yazarServis)
        {
            _yazarServis = yazarServis;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<JsonResult> YazarlariGetir()
        {
            var sonuc = await _yazarServis.YazarlariGetir();
            return Json(sonuc);
        }

        public IActionResult YazarKayit(YazarKayitViewModel model)
        {
            if (model.YazarKey != null)
            {
                return PartialView("~/Views/Yazar/_YazarKayitPartial.cshtml", model);
            }

            return PartialView("~/Views/Yazar/_YazarKayitPartial.cshtml");
        }

        public async Task<SonucModel<YazarKayitViewModel>> YazarKaydet(YazarKayitViewModel model)
        {
            if (model.Ad != null)
            {
                model.Ad = Helper.ToTitleCase(model.Ad);
            }
            var sonuc = await _yazarServis.YazarKaydetGuncelle(model);
            return sonuc;
        }

        public async Task<SonucModel<YazarSilViewModel>> YazarSil(YazarSilViewModel model)
        {
            var sonuc = await _yazarServis.YazarSil(model);
            return sonuc;
        }
    }
}

Lms.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lms.Web</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700|Roboto:300,400,500,600,700">

    <!--end::Fonts -->
    <!--begin::Page Vendors Styles(used by this page) -->
    <link href="~/assets/plugins/custom/fullcalendar/fullcalendar.bundle.css" rel="stylesheet" type="text/css" />

    <!--end::Page Vendors Styles -->
    <!--begin::Global Theme Styles(used by all pages) -->
    <link href="~/assets/plugins/global/plugins.bundle.css" rel="stylesheet" type="text/css" />
    <link href="assets/css/style.bundle.css" rel="stylesheet" type="text/css" />

    <!--end::Global Theme Styles -->
    <!--begin::Layout Skins(used by all pages) -->
    <link href="~/assets/css/skins/header/base/light.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/skins/header/menu/light.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/skins/brand/dark.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/skins/aside/dark.css" rel="stylesheet" type="text/css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!--end::Layout Skins -->
    <link rel="shortcut icon" href="~/assets/media/logos/favicon.ico" />

    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/ej2/material.css" />
    <script src="~/js/ej2/ej2.min.js"></script>

</head>
<body class="kt-quick-panel--right kt-demo-panel--right kt-offcanvas-panel--right kt-header--fixed kt-header-mobile--fixed kt-subheader--enabled kt-subheader--fixed kt-subheader--solid kt-aside--enabled kt-aside--fixed kt-page--loading">

    <div id="kt_header_mobile" class="kt-header-mobile  kt-header-mobile--fixed ">
        <div class="kt-header-mobile__logo">
            <a href="index.html">
                <img alt="Logo" src="~/assets/media/logos/logo-light.png" />
            </a>
        </div>
        <div class="kt-header-mobile__toolbar">
            <button class="kt-header-mobile__toggler kt-header-mobile__toggler--left" id="kt_aside_mobile_toggler"><span></span></button>
            <button class="kt-header-mobile__toggler" id="kt_header_mobile_toggler"><span></span></button>
            <button class="kt-header-mobile__topbar-toggler" id="kt_header_mobile_topbar_toggler"><i class="flaticon-more"></i></button>
        </div>
    </div>

    <div class="kt-grid kt-grid--hor kt-grid--root">
        <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--ver kt-page">

            <!-- begin:: Aside -->
            <!-- Uncomment this to display the close button of the panel
            <button class="kt-aside-close " id="kt_aside_close_btn"><i class="la la-close"></i></button>
            -->
            <div class="kt-aside  kt-aside--fixed  kt-grid__item kt-grid kt-grid--desktop kt-grid--hor-desktop" id="kt_aside">

                <!-- begin:: Aside -->
                <div class="kt-aside__brand kt-grid__item " id="kt_aside_brand">
                    <div class="kt-aside__brand-logo">
                        <a href="index.html">
                            <img alt="Logo" src="~/assets/media/logos/logo-light.png" />
                        </a>
                    </div>
                    <div class="kt-aside__brand-tools">
                        <button class="kt-aside__brand-aside-toggler" id="kt_aside_toggler">
                            <span>
                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                        <polygon points="0 0 24 0 24 24 0 24" />
                                        <path d="M5.29288961,6.70710318 C4.90236532,6.31657888 4.90236532,5.68341391 5.29288961,5.29288961 C5.68341391,4.90236532 6.31657888,4.90236532 6.70710318,5.29288961 L12.7071032,11.2928896 C13.0856821,11.6714686 13.0989277,12.281055 12.7371505,12.675721 L7.23715054,18.675721 C6.86395813,19.08284 6.23139076,19.1103429 5.82427177,18.7371505 C5.41715278,18.3639581 5.38964985,17.7313908 5.76284226,17.3242718 L10.6158586,12.0300721 L5.29288961,6.70710318 Z" fill="#000000" fill-rule="nonzero" transform="translate(8.999997, 11.999999) scale(-1, 1) translate(-8.999997, -11.999999) " />
                                        <path d="M10.7071009,15.7071068 C10.3165766,16.0976311 9.68341162,16.0976311 9.29288733,15.7071068 C8.90236304,15.3165825 8.90236304,14.6834175 9.29288733,14.2928932 L15.2928873,8.29289322 C15.6714663,7.91431428 16.2810527,7.90106866 16.6757187,8.26284586 L22.6757187,13.7628459 C23.0828377,14.1360383 23.1103407,14.7686056 22.7371482,15.1757246 C22.3639558,15.5828436 21.7313885,15.6103465 21.3242695,15.2371541 L16.0300699,10.3841378 L10.7071009,15.7071068 Z" fill="#000000" fill-rule="nonzero" opacity="0.3" transform="translate(15.999997, 11.999999) scale(-1, 1) rotate(-270.000000) translate(-15.999997, -11.999999) " />
                                    </g>
                                </svg>
                            </span>
                            <span>
                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                        <polygon points="0 0 24 0 24 24 0 24" />
                                        <path d="M12.2928955,6.70710318 C11.9023712,6.31657888 11.9023712,5.68341391 12.2928955,5.29288961 C12.6834198,4.90236532 13.3165848,4.90236532 13.7071091,5.29288961 L19.7071091,11.2928896 C20.085688,11.6714686 20.0989336,12.281055 19.7371564,12.675721 L14.2371564,18.675721 C13.863964,19.08284 13.2313966,19.1103429 12.8242777,18.7371505 C12.4171587,18.3639581 12.3896557,17.7313908 12.7628481,17.3242718 L17.6158645,12.0300721 L12.2928955,6.70710318 Z" fill="#000000" fill-rule="nonzero" />
                                        <path d="M3.70710678,15.7071068 C3.31658249,16.0976311 2.68341751,16.0976311 2.29289322,15.7071068 C1.90236893,15.3165825 1.90236893,14.6834175 2.29289322,14.2928932 L8.29289322,8.29289322 C8.67147216,7.91431428 9.28105859,7.90106866 9.67572463,8.26284586 L15.6757246,13.7628459 C16.0828436,14.1360383 16.1103465,14.7686056 15.7371541,15.1757246 C15.3639617,15.5828436 14.7313944,15.6103465 14.3242754,15.2371541 L9.03007575,10.3841378 L3.70710678,15.7071068 Z" fill="#000000" fill-rule="nonzero" opacity="0.3" transform="translate(9.000003, 11.999999) rotate(-270.000000) translate(-9.000003, -11.999999) " />
                                    </g>
                                </svg>
                            </span>
                        </button>

                        <!--
                        <button class="kt-aside__brand-aside-toggler kt-aside__brand-aside-toggler--left" id="kt_aside_toggler"><span></span></button>
                        -->
                    </div>
                </div>

                <!-- end:: Aside -->
                <!-- begin:: Aside Menu -->
                <div class="kt-aside-menu-wrapper kt-grid__item kt-grid__item--fluid" id="kt_aside_menu_wrapper">
                    <div id="kt_aside_menu" class="kt-aside-menu " data-ktmenu-vertical="1" data-ktmenu-scroll="1" data-ktmenu-dropdown-timeout="500">
                        <ul class="kt-menu__nav ">
                            <li class="kt-menu__item " aria-haspopup="true"><a asp-controller="Dashboard" asp-action="Index" class="kt-menu__link "><i class="kt-menu__link-icon flaticon-home"></i><span class="kt-menu__link-text">Dashboard</span></a></li>
                            <li class="kt-menu__item " aria-haspopup="true"><a asp-area="Kutuphane" asp-controller="Kitap" asp-action="Index" class="kt-menu__link "><i class="kt-menu__link-icon flaticon-home"></i><span class="kt-menu__link-text">Kitap</span></a></li>
                            <li class="kt-menu__item " aria-haspopup="true"><a asp-area="Kutuphane" asp-controller="Kategori" asp-action="Index" class="kt-menu__link "><i class="kt-menu__link-icon flaticon-home"></i><span class="kt-menu__link-text">Kategori</span></a></li>
                            <li class="kt-menu__item " aria-haspopup="true"><a asp-area="Kutuphane" asp-controller="Yazar" asp-action="Index" class="kt-menu__link "><i class="kt-menu__link-icon flaticon-home"></i><span class="kt-menu__link-text">Yazar</span></a></li>
                            <li class="kt-menu__item " aria-haspopup="true"><a asp-area="Kutuphane" asp-controller="Yayinevi" asp-action="Index" class="kt-menu__link "><i class="kt-menu__link-icon flaticon-home"></i><span class="kt-menu__link-text">Yayinevi</span></a></li>
                            <li class="kt-menu__item " aria-haspopup="true"><a asp-area="Kutuphane" asp-controller="Uye" asp-action="Index" class="kt-menu__link "><i class="kt-menu__link-icon flaticon-home"></i><span class="kt-menu__link-text">Üyelik</span></a></li>
                        </ul>
                    </div>
                </div>

                <!-- end:: Aside Menu -->
            </div>

            <!-- end:: Aside -->
            <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor kt-wrapper" id="kt_wrapper">

                <!-- begin:: Header -->
                <div id="kt_header" class="kt-header kt-grid__item  kt-header--fixed ">

                    <!-- begin:: Header Menu -->
                    <!-- Uncomment this to display the close button of the panel
                    <button class="kt-header-menu-wrapper-close" id="kt_header_menu_mobile_close_btn"><i class="la la-close"></i></button>
                    -->
                    <div class="kt-header-menu-wrapper" id="kt_header_menu_wrapper">
                        <div id="kt_header_menu" class="kt-header-menu kt-header-menu-mobile  kt-header-menu--layout-default ">
                            <ul class="kt-menu__nav ">
                            </ul>
                        </div>
                    </div>

                    <!-- end:: Header Menu -->
                    <!-- begin:: Header Topbar -->
                    <div class="kt-header__topbar">

                        <!--begin: User Bar -->
                        

                        <!--end: User Bar -->
                    </div>

                    <!-- end:: Header Topbar -->
                </div>

                <!-- end:: Header -->
                <div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor">

                    <!-- begin:: Content -->
                    @RenderBody()

                    <div class="modal fade" id="kt_modal_6" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                            <div id="generalModal" class="modal-content">

                            </div>
                        </div>
                    </div>
                    <!-- end:: Content -->
                </div>

                <!-- begin:: Footer -->
                <div class="kt-footer  kt-grid__item kt-grid kt-grid--desktop kt-grid--ver-desktop" id="kt_footer">
                    <div class="kt-container  kt-container--fluid ">
                        <div class="kt-footer__copyright">
                            2020&nbsp;&copy;&nbsp;<a class="kt-link">Tümer Seyrek</a>
                        </div>
                    </div>
                </div>
                <!-- end:: Footer -->
            </div>
        </div>
    </div>

    <div id="kt_scrolltop" class="kt-scrolltop">
        <i class="fa fa-arrow-up"></i>
    </div>

    <script>
        var KTAppOptions = {
            "colors": {
                "state": {
                    "brand": "#5d78ff",
                    "dark": "#282a3c",
                    "light": "#ffffff",
                    "primary": "#5867dd",
                    "success": "#34bfa3",
                    "info": "#36a3f7",
                    "warning": "#ffb822",
                    "danger": "#fd3995",
                    "red": "#e3165b"
                },
                "base": {
                    "label": [
                        "#c5cbe3",
                        "#a1a8c3",
                        "#3d4465",
                        "#3e4466"
                    ],
                    "shape": [
                        "#f0f3ff",
                        "#d9dffa",
                        "#afb4d4",
                        "#646c9a"
                    ]
                }
            }
        };
    </script>







    <!--begin::Global Theme Bundle(used by all pages) -->
    <script src="~/assets/plugins/global/plugins.bundle.js" type="text/javascript"></script>
    <script src="~/assets/js/scripts.bundle.js" type="text/javascript"></script>
    <!--end::Page Vendors -->
    <!--begin::Page Scripts(used by this page) -->
    <script src="~/assets/js/pages/dashboard.js" type="text/javascript"></script>
    <script src="~/js/jquery.serializeObject.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9.10.13/dist/sweetalert2.all.min.js"></script>
    <script src="~/js/site.js"></script>
    @RenderSection("Scripts", required: false)
    <ejs-scripts></ejs-scripts>


</body>
</html>